title: Tariffs Are Bullshit
baseurl: ""
url: ""

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  show_excerpts: true
  skin: dark

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
